
#pragma region CONSTANTS

#define DEFAULT_PIXELSCALE 2
#define DEFAULT_SCREEN_WIDTH 256u
#define DEFAULT_SCREEN_HEIGHT 224u
#define DEFAULT_FIXEDFRAMERATE 60u
#define DEFAULT_MAXFPS 60u

#pragma endregion CONSTANTS